env:
  es6: true
  node: true
extends: 
  - eslint:recommended
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-spacing:
    - error
    - 
      before: false
      after: true 
  space-infix-ops:
    - error
    - 
      int32Hint: false
  key-spacing:
    - error
    - 
      afterColon: true
  eqeqeq:
    - error
    - allow-null
  no-console:
    - error
    -
      allow:
        - log