

language: node_js

sudo: true

node_js:
  - 8
  - 9

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules

script:
  # - yarn lint
  - yarn run version
  - yarn run test
  # - sudo yarn run start
  # - sudo yarn run reload
  # - sudo yarn run stop


