

language: node_js

sudo: true

node_js:
  - 8
  - 9

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run lint
  - yarn run test
  - yarn run start
  - yarn run reload
  - yarn run stop
  - yarn run version


